---
ansible_user: developer
ansible_password: C1sco12345
ansible_connection: network_cli
ansible_network_os: ios
ansible_port: 22

ntp: "10.10.10.10"

ospf:
  rid: "3.3.3.3"
  area: "0"
  networks:
    - "10.0.0.0 0.0.0.255"
    - "192.168.1.0 0.0.0.255"
    - "172.16.0.0 0.0.255.255"
  redistributing:
    bgp: "65001"