---

- name: "Playbook to test conditional logic"
  hosts: routers
  gather_facts: true
  gather_subset: all
  connection: network_cli

  tasks:
    - name: "Task 1"
      debug:
        msg: "Interface {{ item['key'] }} has an IP address of {{ item['value']['ipv4'][0]['address'] }}"
      loop: "{{ ansible_net_interfaces | dict2items }}"
      when: item['value']['ipv4'] != []