---

- name: "Configure Gig2"
  hosts: routers
  connection: network_cli

  tasks:
    - name: "Configure Gigabit 2 on Routers"
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet2
            ipv4:
              - address: 172.16.32.1/24
        state: merged
      register: cisco_output


    - name: "Print Cisco Output"
      debug:
        msg: "{{ cisco_output }}"
