---
- name: Create loopback payload from template
  hosts: routers
  connection: local

  tasks:
    - name: Create template
      with_items: "{{local_loopback}}"
      template: src="files/ietf_inteface.j2" dest="./output.json"