---
- name: 9k facts
  hosts: 192.168.1.251
  connection: local
  tasks:
    - name: Get Nexus9k facts
      nxos_facts:
        host: nexus
        transport: nxapi
        use_ssl: yes
        validate_certs: no
      register: nxos_data

    - name: Print name to console
      debug: msg="{{nxos_data}}"